 name: Flutter CI/CD
 
 on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout source code
       uses: actions/checkout@v3
 
     - name: Set up Flutter
       uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.24.0' # Matches your Flutter SDK version
         channel: 'stable'

     - name: Install dependencies
       run: flutter pub get
       
     - name: Clean the build directory
       run: flutter clean

     - name: Install dependencies
       run: flutter pub get
 
     - name: Build APK
       run: flutter build apk --release
       
     - name: Upload APK artifact
       uses: actions/upload-artifact@v3
       with:
         name: my-flutter-app-apk
         path: build/app/outputs/flutter-apk/app-release.apk

     - name: Upload APK to InstallOnAir
       run: |
         curl -X POST "https://installonair.com/" \
         -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
         -F "message=New APK from GitHub Actions" \
         -F "release_notes=Uploaded automatically from GitHub Actions"
